### PR TITLE
added react starter files

### PR DESCRIPTION
**Pull request by ucheuzor**
React starter file for the project

### CODE REVIEW

**Review by mpolobe — COMMENTED** [review]
I have had a look at the code. I will approve. Does it have any errors before we merge?

**Review by atoo — CHANGES_REQUESTED** [review]
Please address the 6 issues pointed by codacy in the readme file, or remove that file.
Thank you.

**Review by atoo — APPROVED** [review]
Thank you for fixes.

**Review by jeancheikh — APPROVED** [review]

**Comment by mpolobe** [comment]
Looks fine to me. Check on Codacy. All checks passed

**Comment by mpolobe** [comment]
L

**Comment by mpolobe** [comment]
We can merge this pull request.

**Comment by mpolobe** [comment]
This looks fine now.

**Review by mpolobe — APPROVED** [review]
Looks fine.

**Review by gisely9 — COMMENTED** [review]
I like everything so far

**Review by gisely9 — APPROVED** [review]
good

**Pull request merged**
