### PR TITLE
initial React JS app setup

### PR DESCRIPTION
**Pull request by atoo**
As a recall from the setup by @ucheuzor, we are supposed to work a ReactJS app, not React Native. Here is an initial setup with a Splash, Login and Videos screens. The content of each one is still to be worked, as well as the other screens.

**To run the app locally after cloning the repo:**
- install all node packages from package.json
- install webpack : npm install -g webpack@2
- build the project: webpack --progress --color
- install http-server if you don't have one locally: npm install -g http-server
- start the server in the project root: http-server
- open the provided url in the browser

### CODE REVIEW

**Comment by atoo** [comment]
Fixing errors pointed by Codacy...

**Review by mpolobe — APPROVED** [review]
Approved JS Webpack

**Comment by ucheuzor** [comment]
I'll approve though, but the set up I used was actually React Js and not Native. I don't on mobile apps so I have never set up React Native boilerplate. Though am aware they are similar. What I did was the basic React boilerplate set up just in case. But no big deal. Problem is , I feel setting up webpack from scratch and working with it is kinda bulky

**Review by ucheuzor — APPROVED** [review]

**Comment by atoo** [comment]
> I'll approve though, but the set up I used was actually React Js and not Native. I don't on mobile apps so I have never set up React Native boilerplate. Though am aware they are similar. What I did was the basic React boilerplate set up just in case. But no big deal. Problem is , I feel setting up webpack from scratch and working with it is kinda bulky

Thank you

**Review by gisely9 — APPROVED** [review]
looks good !!

**Pull request merged**
